apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mysql-access
  namespace: network
spec:
  podSelector:
    matchLabels:
      app: web-app
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: mysql-db
    ports:
    - protocol: TCP
      port: 3306
